# Site settings 配置站点
title: '小小草的博客'
description: '这里是小小草自己的blog'
keyword: ''
url: 'http://yourkkc.top' # your host
baseurl: '/'

# Navigation links
nav:
  home: '/index.html'
  tags: '/tags.html'

# Author 配置博主信息
author: '何汇玉'
nickname: '小小草'
bio: 'IT开发者，杂食动物'
avatar: 'assets/img/profile.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: false
disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: ''
  github: '//github.com/yourkkc.github.io'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: false

# Plugins
gems: [jekyll-paginate]